"""Emby integration constants. :copyright: (c) 2026 by Meir Miyara. :license: MPL-2.0"""

EMBY_POLL_INTERVAL = 5
EMBY_API_TIMEOUT = 10
EMBY_CONNECTION_TIMEOUT = 5
EMBY_TICKS_PER_SECOND = 10_000_000

SIMPLE_COMMANDS = [
    "MOVE_UP", "MOVE_DOWN", "MOVE_LEFT", "MOVE_RIGHT",
    "SELECT", "BACK", "GO_HOME", "GO_TO_SETTINGS", "GO_TO_SEARCH",
    "PAGE_UP", "PAGE_DOWN", "NEXT_LETTER", "PREVIOUS_LETTER",
    "TOGGLE_OSD", "TOGGLE_CONTEXT_MENU", "TOGGLE_FULLSCREEN",
    "PLAY_PAUSE", "STOP", "NEXT_TRACK", "PREVIOUS_TRACK",
    "VOLUME_UP", "VOLUME_DOWN", "MUTE_TOGGLE",
]
